# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# qqqq222
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  env:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: hardhat install
      run: npm install hardhat
    - name: Run test
      run: yarn test
      env: 
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }} 
        MNEMONIC: ${{ secrets.MNEMONIC }} 
        ALCHEMY_MATIC: ${{ secrets.ALCHEMY_MATIC }} 
        ALCHEMY_MAINNET: ${{ secrets.ALCHEMY_MAINNET }} 
        ALCHEMY_RINKEBY: ${{ secrets.ALCHEMY_RINKEBY }} 
        ALCHEMY_GOERLI: ${{ secrets.ALCHEMY_GOERLI }} 
        ALCHEMY_KOVAN: ${{ secrets.ALCHEMY_KOVAN }} 
        INFURA_ID_PROJECT: ${{ secrets.INFURA_ID_PROJECT }} 

        
        
